import HomePage from "../pages/Client/HomePage";
import LoginPage from "../pages/Auth/LoginPage";
import RegisterPage from "../pages/Auth/RegisterPage";
import ProductsPage from "../pages/Client/ProductsPage";
import BestSellingPage from "../pages/Client/BestSellingPage";
import FAQPage from "../pages/Client/FAQPage";
import ActivationPage from "../pages/Auth/ActivationPage";
import ProfilePage from "../pages/Client/ProfilePage";
import ProductDetailsPage from "../pages/Client/ProductDetailsPage";
import CheckoutPage from "../pages/Client/CheckoutPage";
import PaymentPage from "../pages/Client/PaymentPage";
import OrderSuccessPage from "../pages/Client/OrderSuccessPage";
import OrderDetailsPage from "../pages/Client/OrderDetailsPage";
import TrackOrderPage from "../pages/Client/TrackOrderPage";
import UserInbox from "../pages/Client/UserInbox";
export { HomePage, LoginPage, RegisterPage, ProductsPage, BestSellingPage, FAQPage, ActivationPage, ProfilePage, ProductDetailsPage, CheckoutPage, PaymentPage, OrderSuccessPage, OrderDetailsPage, TrackOrderPage, UserInbox };
